import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import SiteLayout from "@/components/site-layout/SiteLayout";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><SiteLayout>{children}</SiteLayout></body>
    </html>
  );
}
